package org.green.modules;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.inject.AbstractModule;
import com.google.inject.Provides;
import com.google.inject.name.Names;
import io.prometheus.client.Gauge;

import java.net.URI;
import java.net.http.HttpClient;
import java.util.Collections;
import java.util.List;

import javax.inject.Named;

import org.green.stack.Stack;

public class StackModule extends AbstractModule {
	public static final TypeReference<List<Stack>> STACKS_TYPE_REF = new TypeReference<>() {
    };
    private final String stackServiceEndpoint;
    private final Long stackScrappingInterval;

    public StackModule(String stackServiceEndpoint, Long stackScrappingInterval) {
        this.stackServiceEndpoint = stackServiceEndpoint;
        this.stackScrappingInterval = stackScrappingInterval;
    }

    @Override
    public void configure() {
        bind(URI.class).annotatedWith(Names.named("stackServiceEndpoint")).toInstance(URI.create(stackServiceEndpoint));
        bind(HttpClient.class).toInstance(HttpClient.newBuilder().build());
        bind(Gauge.class).annotatedWith(Names.named("stackGauge"))
                .toInstance(Gauge.build("stackInfo", "Tells if the stack is active(1)/inActive(0)")
                .labelNames("region", "s_id", "type", "name")
                .create()
                .register());
        bind(Long.class).annotatedWith(Names.named("stackScrappingInterval")).toInstance(stackScrappingInterval);
        bind(ObjectMapper.class).toInstance(new ObjectMapper());
    }
    
    @Provides
    @Named("dummyInfo")
    List<Stack> getDummyStack(ObjectMapper mapper) {
    	try {
			return mapper.readValue(CONTENT, STACKS_TYPE_REF);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	return Collections.emptyList();
    }
    
    private static String CONTENT = "[\n"
    		+ "  {\n"
    		+ "    \"id\": 75351707,\n"
    		+ "    \"name\": \"arn:aws:cloudformation:us-east-1:254306680133:stack/RgdfGobTjkZQ/9d2e08c2-0ed9-4902-a616-5bd4d40661ea\",\n"
    		+ "    \"region\": \"us-east-1\",\n"
    		+ "    \"resources\": [\n"
    		+ "      {\n"
    		+ "        \"id\": 30646779,\n"
    		+ "        \"name\": \"EMMSzXCANVMN\",\n"
    		+ "        \"resourceType\": \"AWS::EC2::Instance\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 72560593,\n"
    		+ "        \"name\": \"guNNbWTKqWMG\",\n"
    		+ "        \"resourceType\": \"AWS::ECS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 95001888,\n"
    		+ "        \"name\": \"SnkQErSDdZsL\",\n"
    		+ "        \"resourceType\": \"AWS::EKS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 6956458,\n"
    		+ "        \"name\": \"hbnYSgowjQAE\",\n"
    		+ "        \"resourceType\": \"AWS::ElastiCache::CacheCluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      }\n"
    		+ "    ]\n"
    		+ "  },\n"
    		+ "  {\n"
    		+ "    \"id\": 42350533,\n"
    		+ "    \"name\": \"arn:aws:cloudformation:us-east-2:254306680133:stack/CYECGprQgNDx/22669e5a-7017-4361-89fa-1a7f4e9e2517\",\n"
    		+ "    \"region\": \"us-east-2\",\n"
    		+ "    \"resources\": [\n"
    		+ "      {\n"
    		+ "        \"id\": 92913644,\n"
    		+ "        \"name\": \"yhYaLPCOvuJa\",\n"
    		+ "        \"resourceType\": \"AWS::EC2::Instance\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 44394415,\n"
    		+ "        \"name\": \"uQAOayGwpfqQ\",\n"
    		+ "        \"resourceType\": \"AWS::ECS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 98426516,\n"
    		+ "        \"name\": \"rgNbjwjqqosl\",\n"
    		+ "        \"resourceType\": \"AWS::EKS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 91836424,\n"
    		+ "        \"name\": \"fzCmHTbbBrCi\",\n"
    		+ "        \"resourceType\": \"AWS::ElastiCache::CacheCluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      }\n"
    		+ "    ]\n"
    		+ "  },\n"
    		+ "  {\n"
    		+ "    \"id\": 65986582,\n"
    		+ "    \"name\": \"arn:aws:cloudformation:us-west-1:254306680133:stack/uTEvFbptfizp/958e528a-b855-4c53-97a2-2b03541df1c4\",\n"
    		+ "    \"region\": \"us-west-1\",\n"
    		+ "    \"resources\": [\n"
    		+ "      {\n"
    		+ "        \"id\": 82929235,\n"
    		+ "        \"name\": \"JqUyNjUgdjTh\",\n"
    		+ "        \"resourceType\": \"AWS::EC2::Instance\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 71348782,\n"
    		+ "        \"name\": \"KmYghENjeSnd\",\n"
    		+ "        \"resourceType\": \"AWS::ECS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 62285513,\n"
    		+ "        \"name\": \"xAuZHvvdLJIP\",\n"
    		+ "        \"resourceType\": \"AWS::EKS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 17236069,\n"
    		+ "        \"name\": \"faVmMWlzFfEs\",\n"
    		+ "        \"resourceType\": \"AWS::ElastiCache::CacheCluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      }\n"
    		+ "    ]\n"
    		+ "  },\n"
    		+ "  {\n"
    		+ "    \"id\": 46146115,\n"
    		+ "    \"name\": \"arn:aws:cloudformation:us-west-2:254306680133:stack/ujMJMAVgWTNZ/28ff3b6f-54db-4555-9bd4-022b34d9d011\",\n"
    		+ "    \"region\": \"us-west-2\",\n"
    		+ "    \"resources\": [\n"
    		+ "      {\n"
    		+ "        \"id\": 69227192,\n"
    		+ "        \"name\": \"iPbxCHnHQfTo\",\n"
    		+ "        \"resourceType\": \"AWS::EC2::Instance\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 30744728,\n"
    		+ "        \"name\": \"NxvTWMkfRbJl\",\n"
    		+ "        \"resourceType\": \"AWS::ECS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 13574019,\n"
    		+ "        \"name\": \"ZZkXyefrCVLj\",\n"
    		+ "        \"resourceType\": \"AWS::EKS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 24377727,\n"
    		+ "        \"name\": \"MTAYpeEBOZlq\",\n"
    		+ "        \"resourceType\": \"AWS::ElastiCache::CacheCluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      }\n"
    		+ "    ]\n"
    		+ "  },\n"
    		+ "  {\n"
    		+ "    \"id\": 46629925,\n"
    		+ "    \"name\": \"arn:aws:cloudformation:ca-central-1:254306680133:stack/ngZmDjinFXRj/dd1536b4-dbe6-45ce-9dc7-4afb50278e96\",\n"
    		+ "    \"region\": \"ca-central-1\",\n"
    		+ "    \"resources\": [\n"
    		+ "      {\n"
    		+ "        \"id\": 83340083,\n"
    		+ "        \"name\": \"MSnVZpevEtFd\",\n"
    		+ "        \"resourceType\": \"AWS::EC2::Instance\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 2404109,\n"
    		+ "        \"name\": \"djEsAjDVFBsR\",\n"
    		+ "        \"resourceType\": \"AWS::ECS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 34334220,\n"
    		+ "        \"name\": \"JdPqqpwjoMhR\",\n"
    		+ "        \"resourceType\": \"AWS::EKS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 29473928,\n"
    		+ "        \"name\": \"pWrNwHVWcVLS\",\n"
    		+ "        \"resourceType\": \"AWS::ElastiCache::CacheCluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      }\n"
    		+ "    ]\n"
    		+ "  },\n"
    		+ "  {\n"
    		+ "    \"id\": 14772840,\n"
    		+ "    \"name\": \"arn:aws:cloudformation:eu-north-1:254306680133:stack/DeRwkGMfFanT/00d7e03b-940a-415f-a80a-c2ab716ebb96\",\n"
    		+ "    \"region\": \"eu-north-1\",\n"
    		+ "    \"resources\": [\n"
    		+ "      {\n"
    		+ "        \"id\": 27636222,\n"
    		+ "        \"name\": \"tWEudSKWBnNG\",\n"
    		+ "        \"resourceType\": \"AWS::EC2::Instance\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 705755,\n"
    		+ "        \"name\": \"WjniDOwIJaNj\",\n"
    		+ "        \"resourceType\": \"AWS::ECS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 65534434,\n"
    		+ "        \"name\": \"sGsRLXwHGxZb\",\n"
    		+ "        \"resourceType\": \"AWS::EKS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 82341544,\n"
    		+ "        \"name\": \"IXeBPxwflSSG\",\n"
    		+ "        \"resourceType\": \"AWS::ElastiCache::CacheCluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      }\n"
    		+ "    ]\n"
    		+ "  },\n"
    		+ "  {\n"
    		+ "    \"id\": 36769132,\n"
    		+ "    \"name\": \"arn:aws:cloudformation:eu-west-1:254306680133:stack/ZfxLmOqaPHtl/0fea5a12-fe44-4eac-a435-25c538bff322\",\n"
    		+ "    \"region\": \"eu-west-1\",\n"
    		+ "    \"resources\": [\n"
    		+ "      {\n"
    		+ "        \"id\": 22088031,\n"
    		+ "        \"name\": \"dQmFJbHUGnlI\",\n"
    		+ "        \"resourceType\": \"AWS::EC2::Instance\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 37740634,\n"
    		+ "        \"name\": \"rIhOUTSanEbW\",\n"
    		+ "        \"resourceType\": \"AWS::ECS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 88030283,\n"
    		+ "        \"name\": \"WYYiOHTVFZGh\",\n"
    		+ "        \"resourceType\": \"AWS::EKS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 67926015,\n"
    		+ "        \"name\": \"wFLgLAnzBnzX\",\n"
    		+ "        \"resourceType\": \"AWS::ElastiCache::CacheCluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      }\n"
    		+ "    ]\n"
    		+ "  },\n"
    		+ "  {\n"
    		+ "    \"id\": 62249511,\n"
    		+ "    \"name\": \"arn:aws:cloudformation:eu-west-2:254306680133:stack/xnDKtnzqjwzZ/143f6a47-4d6e-4167-8cb7-364702d70b0a\",\n"
    		+ "    \"region\": \"eu-west-2\",\n"
    		+ "    \"resources\": [\n"
    		+ "      {\n"
    		+ "        \"id\": 25922345,\n"
    		+ "        \"name\": \"cgUDEByiHGKb\",\n"
    		+ "        \"resourceType\": \"AWS::EC2::Instance\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 57937193,\n"
    		+ "        \"name\": \"bwStfxCOmqGB\",\n"
    		+ "        \"resourceType\": \"AWS::ECS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 78029312,\n"
    		+ "        \"name\": \"QxOrgWTWxhWQ\",\n"
    		+ "        \"resourceType\": \"AWS::EKS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 7400563,\n"
    		+ "        \"name\": \"iteSjsnwsMgv\",\n"
    		+ "        \"resourceType\": \"AWS::ElastiCache::CacheCluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      }\n"
    		+ "    ]\n"
    		+ "  },\n"
    		+ "  {\n"
    		+ "    \"id\": 39072300,\n"
    		+ "    \"name\": \"arn:aws:cloudformation:eu-west-3:254306680133:stack/NtMddpmLIcYe/f3982f74-1c50-48ed-af1d-cf4f590c2bb4\",\n"
    		+ "    \"region\": \"eu-west-3\",\n"
    		+ "    \"resources\": [\n"
    		+ "      {\n"
    		+ "        \"id\": 18412133,\n"
    		+ "        \"name\": \"mtmTptvMHdAU\",\n"
    		+ "        \"resourceType\": \"AWS::EC2::Instance\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 36757149,\n"
    		+ "        \"name\": \"RMprYUyNZxKK\",\n"
    		+ "        \"resourceType\": \"AWS::ECS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 69521364,\n"
    		+ "        \"name\": \"wZkIdYyYVmeJ\",\n"
    		+ "        \"resourceType\": \"AWS::EKS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 22934761,\n"
    		+ "        \"name\": \"GYxlQbxBlMeW\",\n"
    		+ "        \"resourceType\": \"AWS::ElastiCache::CacheCluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      }\n"
    		+ "    ]\n"
    		+ "  },\n"
    		+ "  {\n"
    		+ "    \"id\": 3636731,\n"
    		+ "    \"name\": \"arn:aws:cloudformation:eu-central-1:254306680133:stack/tGFzCtgbUvPs/cfcd9945-983e-4b95-ac9d-c9a65ebb693d\",\n"
    		+ "    \"region\": \"eu-central-1\",\n"
    		+ "    \"resources\": [\n"
    		+ "      {\n"
    		+ "        \"id\": 84975302,\n"
    		+ "        \"name\": \"wPnmxaSUFemN\",\n"
    		+ "        \"resourceType\": \"AWS::EC2::Instance\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 45143077,\n"
    		+ "        \"name\": \"eOFGbTsJJquH\",\n"
    		+ "        \"resourceType\": \"AWS::ECS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 90960483,\n"
    		+ "        \"name\": \"jdWHGAuVSCeS\",\n"
    		+ "        \"resourceType\": \"AWS::EKS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 33317174,\n"
    		+ "        \"name\": \"MHgxltXgPIij\",\n"
    		+ "        \"resourceType\": \"AWS::ElastiCache::CacheCluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      }\n"
    		+ "    ]\n"
    		+ "  },\n"
    		+ "  {\n"
    		+ "    \"id\": 34425702,\n"
    		+ "    \"name\": \"arn:aws:cloudformation:eu-south-1:254306680133:stack/JfXcGppdHwvM/017d4b06-7f0d-4995-93b1-91b0db5ac0cc\",\n"
    		+ "    \"region\": \"eu-south-1\",\n"
    		+ "    \"resources\": [\n"
    		+ "      {\n"
    		+ "        \"id\": 77530255,\n"
    		+ "        \"name\": \"QWULhcszlnEk\",\n"
    		+ "        \"resourceType\": \"AWS::EC2::Instance\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 26033434,\n"
    		+ "        \"name\": \"KXEVqJeKPUwc\",\n"
    		+ "        \"resourceType\": \"AWS::ECS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 62880652,\n"
    		+ "        \"name\": \"IeDLTEgrsuTl\",\n"
    		+ "        \"resourceType\": \"AWS::EKS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 74436368,\n"
    		+ "        \"name\": \"eYfdwtjKdpzE\",\n"
    		+ "        \"resourceType\": \"AWS::ElastiCache::CacheCluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      }\n"
    		+ "    ]\n"
    		+ "  },\n"
    		+ "  {\n"
    		+ "    \"id\": 56103091,\n"
    		+ "    \"name\": \"arn:aws:cloudformation:af-south-1:254306680133:stack/IMUyXCIrNlGk/c7a11475-bf8e-4eff-9f6f-098ae5e62239\",\n"
    		+ "    \"region\": \"af-south-1\",\n"
    		+ "    \"resources\": [\n"
    		+ "      {\n"
    		+ "        \"id\": 74467447,\n"
    		+ "        \"name\": \"MfpqnFNqkxDQ\",\n"
    		+ "        \"resourceType\": \"AWS::EC2::Instance\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 30266619,\n"
    		+ "        \"name\": \"rInQIxysqkMl\",\n"
    		+ "        \"resourceType\": \"AWS::ECS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 11545301,\n"
    		+ "        \"name\": \"BnEywmgejCYD\",\n"
    		+ "        \"resourceType\": \"AWS::EKS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 10091917,\n"
    		+ "        \"name\": \"KjwzCQxetwlR\",\n"
    		+ "        \"resourceType\": \"AWS::ElastiCache::CacheCluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      }\n"
    		+ "    ]\n"
    		+ "  },\n"
    		+ "  {\n"
    		+ "    \"id\": 5841854,\n"
    		+ "    \"name\": \"arn:aws:cloudformation:ap-northeast-1:254306680133:stack/GqZvAJSXSwwS/ef23a8ed-1b8f-4346-b953-84e5dff95163\",\n"
    		+ "    \"region\": \"ap-northeast-1\",\n"
    		+ "    \"resources\": [\n"
    		+ "      {\n"
    		+ "        \"id\": 46955421,\n"
    		+ "        \"name\": \"jDwvjyLqRTcs\",\n"
    		+ "        \"resourceType\": \"AWS::EC2::Instance\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 22042285,\n"
    		+ "        \"name\": \"aKWIqefygwyi\",\n"
    		+ "        \"resourceType\": \"AWS::ECS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 8179685,\n"
    		+ "        \"name\": \"yviwjzdoFhVG\",\n"
    		+ "        \"resourceType\": \"AWS::EKS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 13732695,\n"
    		+ "        \"name\": \"WakbLBcpCCHx\",\n"
    		+ "        \"resourceType\": \"AWS::ElastiCache::CacheCluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      }\n"
    		+ "    ]\n"
    		+ "  },\n"
    		+ "  {\n"
    		+ "    \"id\": 27923490,\n"
    		+ "    \"name\": \"arn:aws:cloudformation:ap-northeast-2:254306680133:stack/xHwireraOMIM/0247be26-4fb8-4b5a-a1df-ff5a51ca82a8\",\n"
    		+ "    \"region\": \"ap-northeast-2\",\n"
    		+ "    \"resources\": [\n"
    		+ "      {\n"
    		+ "        \"id\": 81989136,\n"
    		+ "        \"name\": \"eMjJNqmFswhe\",\n"
    		+ "        \"resourceType\": \"AWS::EC2::Instance\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 68204434,\n"
    		+ "        \"name\": \"iDisLIahyyBW\",\n"
    		+ "        \"resourceType\": \"AWS::ECS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 91514724,\n"
    		+ "        \"name\": \"hqHnDCavAyji\",\n"
    		+ "        \"resourceType\": \"AWS::EKS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 54452088,\n"
    		+ "        \"name\": \"KSWxLTqyMJgO\",\n"
    		+ "        \"resourceType\": \"AWS::ElastiCache::CacheCluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      }\n"
    		+ "    ]\n"
    		+ "  },\n"
    		+ "  {\n"
    		+ "    \"id\": 47819273,\n"
    		+ "    \"name\": \"arn:aws:cloudformation:ap-northeast-3:254306680133:stack/xhOgDDVgFxyn/67ba26ee-aafa-4e11-8f79-6a53469479a3\",\n"
    		+ "    \"region\": \"ap-northeast-3\",\n"
    		+ "    \"resources\": [\n"
    		+ "      {\n"
    		+ "        \"id\": 47678633,\n"
    		+ "        \"name\": \"ohWPfzneapgb\",\n"
    		+ "        \"resourceType\": \"AWS::EC2::Instance\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 64937843,\n"
    		+ "        \"name\": \"lmmCCrHwsqHk\",\n"
    		+ "        \"resourceType\": \"AWS::ECS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 77021361,\n"
    		+ "        \"name\": \"IXMFdTRvxphr\",\n"
    		+ "        \"resourceType\": \"AWS::EKS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 5712148,\n"
    		+ "        \"name\": \"ORLZZBxoGYZZ\",\n"
    		+ "        \"resourceType\": \"AWS::ElastiCache::CacheCluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      }\n"
    		+ "    ]\n"
    		+ "  },\n"
    		+ "  {\n"
    		+ "    \"id\": 72598731,\n"
    		+ "    \"name\": \"arn:aws:cloudformation:ap-southeast-1:254306680133:stack/RFMExbZqgxxm/d25344c3-8708-409f-a3de-fb47bcaa37d4\",\n"
    		+ "    \"region\": \"ap-southeast-1\",\n"
    		+ "    \"resources\": [\n"
    		+ "      {\n"
    		+ "        \"id\": 81373989,\n"
    		+ "        \"name\": \"pvIuulFUyHLb\",\n"
    		+ "        \"resourceType\": \"AWS::EC2::Instance\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 6167088,\n"
    		+ "        \"name\": \"UERuwSevQKPT\",\n"
    		+ "        \"resourceType\": \"AWS::ECS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 25953038,\n"
    		+ "        \"name\": \"eivzVQIDmRcd\",\n"
    		+ "        \"resourceType\": \"AWS::EKS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 65801170,\n"
    		+ "        \"name\": \"SFZykXLhASur\",\n"
    		+ "        \"resourceType\": \"AWS::ElastiCache::CacheCluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      }\n"
    		+ "    ]\n"
    		+ "  },\n"
    		+ "  {\n"
    		+ "    \"id\": 1352108,\n"
    		+ "    \"name\": \"arn:aws:cloudformation:ap-southeast-2:254306680133:stack/MCTqYnHYxKWH/f467a85d-37ba-4ce5-9f2b-fcd07e5e361f\",\n"
    		+ "    \"region\": \"ap-southeast-2\",\n"
    		+ "    \"resources\": [\n"
    		+ "      {\n"
    		+ "        \"id\": 42304899,\n"
    		+ "        \"name\": \"CHiTUcmfivrS\",\n"
    		+ "        \"resourceType\": \"AWS::EC2::Instance\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 50035082,\n"
    		+ "        \"name\": \"EsoshULgJzQy\",\n"
    		+ "        \"resourceType\": \"AWS::ECS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 7192049,\n"
    		+ "        \"name\": \"QixNHQaflEpS\",\n"
    		+ "        \"resourceType\": \"AWS::EKS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 10379029,\n"
    		+ "        \"name\": \"rxcsXWOTOwNd\",\n"
    		+ "        \"resourceType\": \"AWS::ElastiCache::CacheCluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      }\n"
    		+ "    ]\n"
    		+ "  },\n"
    		+ "  {\n"
    		+ "    \"id\": 4218556,\n"
    		+ "    \"name\": \"arn:aws:cloudformation:ap-southeast-3:254306680133:stack/wHEkiudTAvFI/b2b55e20-1ee4-49cd-a9bc-7a1f10ed3947\",\n"
    		+ "    \"region\": \"ap-southeast-3\",\n"
    		+ "    \"resources\": [\n"
    		+ "      {\n"
    		+ "        \"id\": 65013680,\n"
    		+ "        \"name\": \"mDRSGdVHqluo\",\n"
    		+ "        \"resourceType\": \"AWS::EC2::Instance\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 98993335,\n"
    		+ "        \"name\": \"ofkFpqjxJWeP\",\n"
    		+ "        \"resourceType\": \"AWS::ECS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 38226635,\n"
    		+ "        \"name\": \"LAVmGQVrtKhc\",\n"
    		+ "        \"resourceType\": \"AWS::EKS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 36109741,\n"
    		+ "        \"name\": \"QhPDUexZvymN\",\n"
    		+ "        \"resourceType\": \"AWS::ElastiCache::CacheCluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      }\n"
    		+ "    ]\n"
    		+ "  },\n"
    		+ "  {\n"
    		+ "    \"id\": 6258724,\n"
    		+ "    \"name\": \"arn:aws:cloudformation:ap-east-1:254306680133:stack/iMfXMujrNlcH/926b8136-54e8-4935-b1a4-3f2f50525a49\",\n"
    		+ "    \"region\": \"ap-east-1\",\n"
    		+ "    \"resources\": [\n"
    		+ "      {\n"
    		+ "        \"id\": 70358916,\n"
    		+ "        \"name\": \"AVoOwJdNkkGM\",\n"
    		+ "        \"resourceType\": \"AWS::EC2::Instance\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 952194,\n"
    		+ "        \"name\": \"eJDoRKZfUPnP\",\n"
    		+ "        \"resourceType\": \"AWS::ECS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 64475223,\n"
    		+ "        \"name\": \"lGtrOrnbQrjK\",\n"
    		+ "        \"resourceType\": \"AWS::EKS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 57699379,\n"
    		+ "        \"name\": \"eoZDxOChWxTU\",\n"
    		+ "        \"resourceType\": \"AWS::ElastiCache::CacheCluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      }\n"
    		+ "    ]\n"
    		+ "  },\n"
    		+ "  {\n"
    		+ "    \"id\": 25830029,\n"
    		+ "    \"name\": \"arn:aws:cloudformation:ap-south-1:254306680133:stack/oOFdpTdeJMyO/47a81917-f822-40e5-99b2-97d04295a238\",\n"
    		+ "    \"region\": \"ap-south-1\",\n"
    		+ "    \"resources\": [\n"
    		+ "      {\n"
    		+ "        \"id\": 3176231,\n"
    		+ "        \"name\": \"fukMODBnpBdA\",\n"
    		+ "        \"resourceType\": \"AWS::EC2::Instance\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 15133243,\n"
    		+ "        \"name\": \"XYpFXvWChFgC\",\n"
    		+ "        \"resourceType\": \"AWS::ECS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 32761359,\n"
    		+ "        \"name\": \"UYWfPyndIoxn\",\n"
    		+ "        \"resourceType\": \"AWS::EKS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 37562680,\n"
    		+ "        \"name\": \"qujQbElGdDvC\",\n"
    		+ "        \"resourceType\": \"AWS::ElastiCache::CacheCluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      }\n"
    		+ "    ]\n"
    		+ "  },\n"
    		+ "  {\n"
    		+ "    \"id\": 82764874,\n"
    		+ "    \"name\": \"arn:aws:cloudformation:sa-east-1:254306680133:stack/rkTZOZkIrdyE/c66c4697-7012-43b7-9326-24bd52eb0544\",\n"
    		+ "    \"region\": \"sa-east-1\",\n"
    		+ "    \"resources\": [\n"
    		+ "      {\n"
    		+ "        \"id\": 3846377,\n"
    		+ "        \"name\": \"nngMaJdIqpoj\",\n"
    		+ "        \"resourceType\": \"AWS::EC2::Instance\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 24469716,\n"
    		+ "        \"name\": \"MdVLPvTUWNSf\",\n"
    		+ "        \"resourceType\": \"AWS::ECS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 88981782,\n"
    		+ "        \"name\": \"QYVoeAHRGvcj\",\n"
    		+ "        \"resourceType\": \"AWS::EKS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 51405209,\n"
    		+ "        \"name\": \"kMrIweEnIGCg\",\n"
    		+ "        \"resourceType\": \"AWS::ElastiCache::CacheCluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      }\n"
    		+ "    ]\n"
    		+ "  },\n"
    		+ "  {\n"
    		+ "    \"id\": 55250068,\n"
    		+ "    \"name\": \"arn:aws:cloudformation:me-south-1:254306680133:stack/mCcVBtXPiEkj/7a8af4a4-a5f4-4c01-abfd-3c80f7c6c4b7\",\n"
    		+ "    \"region\": \"me-south-1\",\n"
    		+ "    \"resources\": [\n"
    		+ "      {\n"
    		+ "        \"id\": 67578058,\n"
    		+ "        \"name\": \"wRUAOumyNFcD\",\n"
    		+ "        \"resourceType\": \"AWS::EC2::Instance\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 1335474,\n"
    		+ "        \"name\": \"KYLbCWbXbzDX\",\n"
    		+ "        \"resourceType\": \"AWS::ECS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 50496800,\n"
    		+ "        \"name\": \"yGeLlHNuYgMi\",\n"
    		+ "        \"resourceType\": \"AWS::EKS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 3187779,\n"
    		+ "        \"name\": \"TDZLNSGnDHXL\",\n"
    		+ "        \"resourceType\": \"AWS::ElastiCache::CacheCluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      }\n"
    		+ "    ]\n"
    		+ "  },\n"
    		+ "  {\n"
    		+ "    \"id\": 77782661,\n"
    		+ "    \"name\": \"arn:aws:cloudformation:cn-north-1:254306680133:stack/VepgVPFDwFbh/aefc3cae-d1ba-4daf-b145-f4a5fc82b028\",\n"
    		+ "    \"region\": \"cn-north-1\",\n"
    		+ "    \"resources\": [\n"
    		+ "      {\n"
    		+ "        \"id\": 14657796,\n"
    		+ "        \"name\": \"jcpFZYCxopSK\",\n"
    		+ "        \"resourceType\": \"AWS::EC2::Instance\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 36763946,\n"
    		+ "        \"name\": \"cwOJOBKswBCh\",\n"
    		+ "        \"resourceType\": \"AWS::ECS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 15802190,\n"
    		+ "        \"name\": \"ABpnSllYcZyk\",\n"
    		+ "        \"resourceType\": \"AWS::EKS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 33173569,\n"
    		+ "        \"name\": \"FxSZBsesgDDZ\",\n"
    		+ "        \"resourceType\": \"AWS::ElastiCache::CacheCluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      }\n"
    		+ "    ]\n"
    		+ "  },\n"
    		+ "  {\n"
    		+ "    \"id\": 16805638,\n"
    		+ "    \"name\": \"arn:aws:cloudformation:cn-northwest-1:254306680133:stack/ovhaAuzFvyqK/37cec54b-9100-4a0b-91b9-9c1f882e79bf\",\n"
    		+ "    \"region\": \"cn-northwest-1\",\n"
    		+ "    \"resources\": [\n"
    		+ "      {\n"
    		+ "        \"id\": 83938905,\n"
    		+ "        \"name\": \"TmagIrDLpsWI\",\n"
    		+ "        \"resourceType\": \"AWS::EC2::Instance\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 42422505,\n"
    		+ "        \"name\": \"BJgTroLVdtHC\",\n"
    		+ "        \"resourceType\": \"AWS::ECS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 84233102,\n"
    		+ "        \"name\": \"WOiCQpNBNDSL\",\n"
    		+ "        \"resourceType\": \"AWS::EKS::Cluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      },\n"
    		+ "      {\n"
    		+ "        \"id\": 58445523,\n"
    		+ "        \"name\": \"MBAsYbbzHmnO\",\n"
    		+ "        \"resourceType\": \"AWS::ElastiCache::CacheCluster\",\n"
    		+ "        \"status\": \"CREATE_COMPLETE\"\n"
    		+ "      }\n"
    		+ "    ]\n"
    		+ "  }\n"
    		+ "]\n"
    		+ "";
}
