{
 "title": "CarbonEmisions Demo",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "locations", "query": { "query": "carbonEmission" } },
   { "name": "stackRegion", "query": { "query": "stackInfo" } },
   { "name": "rs_name", "query": { "query": "stackInfo" } },
   { "name": "stackId", "query": { "query": "stackInfo" } },
   { "name": "rs_type", "query": { "query": "stackInfo" } }
  ]
 },
 "panels": [
  {
   "title": "median delta",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "carbonEmission{location=~\"$locations\"} - agg:median:carbonEmission:1d{location=~\"$locations\"}",
     "legendFormat": " carbon enfficency delta: {{location}}"
    }
   ]
  },
  {
   "title": "Current CarbonEmisions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kg/kwh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "carbonEmission{location=~\"$locations\"}",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "stack usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "stackInfo{name=~'$rs_name', region=~'$stackRegion', s_id=~'$stackId', type=~'$rs_type'}",
     "legendFormat": "stackId-{{s_id}} | {{region}} | {{type}} | {{name}}"
    }
   ]
  }
 ]
}